---
title: "Corn and Soy Shock Dashboards"
author: "Mandy Liesch"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)
library(tidyverse)

landUse<-read_csv("LandUse_Shocks.csv")

vegShocks<-read_csv("Vegetative_Shocks.csv")

LUColors <- c("UrbanLand"="#C80813FF", "Tundra"="#71D0F5FF", 
              "Rock/Ice/Desert"="#8A9197FF", "Cropland" = "#FED439FF",
              "HarvCropLand"="#FED439FF", "OtherArableLand" = "#D2AF81FF", 
              "Pasture"= "#FD8CC1FF", "UnmanagedPasture"="#370335FF", 
              "Grassland" = "#46732EFF", "Forest" = "#075149FF", 
              "Shrubland" = "#F05C3BFF", "otherNotArable"="#8A9197FF")

# Vegetative Based Color Pallet
vegCEmissions<-c("#46732EFF")

ModelColors<- c("FAO"="#370335FF", "Houghton" = "#FED439FF", 
                "GCAM" = "#FED439FF", "HWSD"="#1A9993FF", "SG17" = "#197EC0FF",
                "SG20"="#F05C3BFF")

#Break up the land leaf columns into subsets 
#(each land leaf has 4 different categories)
new_LU<-landUse %>% 
  separate(LandLeaf, c("LandUse", "Basin", "Water", "Input")) %>%
  separate(scenario, into = c('scenario', 'date'), sep = ",") %>%
  select(-c("date", "Basin", "Units"))


#Sum together all of the land leaf files by land use type
sum_new_LU<- new_LU %>% 
  group_by(scenario, LandUse) %>% 
  summarise(across(where(is.numeric), sum))

#Reclassify land use types into broader categories
cat_LU<-sum_new_LU %>% 
  mutate(Category = case_when(
  #Cropland category  
  LandUse %in% 
    #Biomass Crops
    c("biomassGrass", "biomassTree",  
    #Fodder Crops
      "FodderGrass", "FodderHerb", 
    #Grain Crops
      "Corn",  "Soybean", "Wheat", "OtherGrain",
    #Oil Crops
      "OilCrop", "Rapeseed", 
    #Other Crops
      "FiberCrop", "MiscCrop", "RootTuber",  "SugarCrop") 
    #Land Use Name
      ~ "HarvCropLand",
    #Other Arable Land
    LandUse == "OtherArableLand" ~"OtherArableLand",
    #Forest categories
    LandUse %in% c("Forest", "UnmanagedForest", "ProtectedUnmanagedForest")
                ~ "Forest",
    #Grassland categories
    LandUse %in% c("Grassland", "ProtectedGrassland") ~ "Grassland", 
    #Pasture category
    LandUse=="Pasture" ~ "Pasture",
    #Unamanged pasture category
    LandUse %in% c("ProtectedUnmanagedPasture", "UnmanagedPasture") 
              ~ "UnmanagedPasture",
    #Shrubland category
    LandUse %in% c("Shrubland", "ProtectedShrubland") ~ "Shrubland",
    #Other categories
    LandUse=="Tundra" ~ "Tundra",
    LandUse=="UrbanLand" ~ "UrbanLand",
    #Default Return Statement
    TRUE~NA_character_
  )
)

#Sum everything up by defined land use category
sum_cat_LU<-cat_LU %>% 
  group_by(scenario, Category) %>% 
  summarise(across(where(is.numeric), sum))

#Create a long dataframe with land use, years, and area 
wide_sum_LU<-sum_cat_LU %>% 
  pivot_longer(!c(scenario, Category), names_to=c("year"), values_to = "area") %>%
  #convert years into the numeric values
  mutate(year = as.numeric(year)) %>% 
  pivot_wider(names_from = scenario, values_from = c(area)) %>%
  mutate(DifCornShock = CORN1BG - BASE) %>%
  mutate(DifSoyShock = SOY1BG - BASE) %>%
  mutate(soyMinCorn = SOY1BG- CORN1BG)

#Break up the land leaf columns into subsets 
#(each land leaf has 4 different categories)
new_veg<-vegShocks %>% 
  separate(LandLeaf, c("LandUse", "Basin", "Water", "Input")) %>%
  separate(scenario, into = c('scenario', 'date'), sep = ",") %>%
  select(-c("date", "Basin", "Units"))


#Sum together all of the land leaf files by land use type
sum_new_veg<- new_veg %>% 
  group_by(scenario, LandUse) %>% 
  summarise(across(where(is.numeric), sum))

#Reclassify land use types into broader categories
cat_veg<-sum_new_veg %>% 
  mutate(Category = case_when(
  #Cropland category  
  LandUse %in% 
    #Biomass Crops
    c("biomassGrass", "biomassTree",  
    #Fodder Crops
      "FodderGrass", "FodderHerb", 
    #Grain Crops
      "Corn",  "Soybean", "Wheat", "OtherGrain",
    #Oil Crops
      "OilCrop", "Rapeseed", 
    #Other Crops
      "FiberCrop", "MiscCrop", "RootTuber",  "SugarCrop") 
    #Land Use Name
      ~ "HarvCropLand",
    #Other Arable Land
    LandUse == "OtherArableLand" ~"OtherArableLand",
    #Forest categories
    LandUse %in% c("Forest", "UnmanagedForest", "ProtectedUnmanagedForest")
                ~ "Forest",
    #Grassland categories
    LandUse %in% c("Grassland", "ProtectedGrassland") ~ "Grassland", 
    #Pasture category
    LandUse=="Pasture" ~ "Pasture",
    #Unamanged pasture category
    LandUse %in% c("ProtectedUnmanagedPasture", "UnmanagedPasture") 
              ~ "UnmanagedPasture",
    #Shrubland category
    LandUse %in% c("Shrubland", "ProtectedShrubland") ~ "Shrubland",
    #Other categories
    LandUse=="Tundra" ~ "Tundra",
    LandUse=="UrbanLand" ~ "UrbanLand",
    #Default Return Statement
    TRUE~NA_character_
  )
)

#Sum everything up by defined land use category
sum_cat_veg<-cat_veg %>% 
  group_by(scenario, Category) %>% 
  summarise(across(where(is.numeric), sum)) %>%
  select(scenario:'2060')


#Create a long dataframe with land use, years, and area 
wide_sum_veg<-sum_cat_veg  %>% 
  pivot_longer(!c(scenario, Category), names_to=c("year"), values_to = "area") %>%
  #convert years into the numeric values
  mutate(year = as.numeric(year)) %>% 
  pivot_wider(names_from = scenario, values_from = c(area)) %>%
  mutate(DifCornShock = CORN1BG - BASE) %>%
  mutate(DifSoyShock = SOY1BG - BASE) 




#Create a series loop to read in all of the data

#Create a list of all .csv files in the output folder
files <- list.files(path="~/github/GCAMShocks/GCAM_Shocks/Shocks", pattern = "\\values.csv$", 
                    full.names = TRUE)

#Initialize an empty list to store data frames
data_list <- list()

# Loop over each file and read it into a data frame
for (file in files) {
  data <- read.csv(file)
  data_list[[file]] <- data
}

# Combine all data frames into one
combined_shock_soil_data <- bind_rows(data_list)

new_Soil_Shock_Emiss<- combined_shock_soil_data %>% 
  separate(LandLeaf, c("LandUse", "Basin", "Water", "Input")) %>%
  separate(scenario, into = c('scenario', 'date'), sep = ",") %>%
  select(-c("date", "region", "Basin", "Units"))  %>%
  select(Series:'X2060')

#Sum together all of the land leaf files by land use type
sum_new_Soil_Emiss<- new_Soil_Shock_Emiss %>% 
  group_by(Series, scenario, LandUse) %>% 
  summarise(across(where(is.numeric), sum))

#Reclassify land use types into broader categories
cat_Soil_Emiss<-sum_new_Soil_Emiss %>% 
  mutate(Category = case_when(
  #Cropland category  
  LandUse %in% 
    #Biomass Crops
    c("biomassGrass", "biomassTree",  
    #Fodder Crops
      "FodderGrass", "FodderHerb", 
    #Grain Crops
      "Corn",  "Soybean", "Wheat", "OtherGrain",
    #Oil Crops
      "OilCrop", "Rapeseed", 
    #Other Crops
      "FiberCrop", "MiscCrop", "RootTuber",  "SugarCrop") 
    #Land Use Name
      ~ "HarvCropLand",
    #Other Arable Land
    LandUse == "OtherArableLand" ~"OtherArableLand",
    #Forest categories
    LandUse %in% c("Forest", "UnmanagedForest", "ProtectedUnmanagedForest")
                ~ "Forest",
    #Grassland categories
    LandUse %in% c("Grassland", "ProtectedGrassland") ~ "Grassland", 
    #Pasture category
    LandUse=="Pasture" ~ "Pasture",
    #Unamanged pasture category
    LandUse %in% c("ProtectedUnmanagedPasture", "UnmanagedPasture") 
              ~ "UnmanagedPasture",
    #Shrubland category
    LandUse %in% c("Shrubland", "ProtectedShrubland") ~ "Shrubland",
    #Other categories
    LandUse=="Tundra" ~ "Tundra",
    LandUse=="UrbanLand" ~ "UrbanLand",
    #Default Return Statement
    TRUE~NA_character_
  )
)

#Sum everything up by defined land use category
sum_cat_soil_emiss<- cat_Soil_Emiss %>% 
  group_by(Series, scenario, Category) %>% 
  summarise(across(where(is.numeric), sum))

#Create a long dataframe with land use, years, and area 
wide_sum_soil_emiss<- sum_cat_soil_emiss %>% 
  pivot_longer(!c(Series, scenario, Category), names_to=c("year"), values_to = "area") %>%
  #Remove the extra X value from the dataset
  mutate(across(c('year'), substr, 2, nchar(year))) %>%
  #convert years into the numeric values
  mutate(year = as.numeric(year)) %>% 
  pivot_wider(names_from = scenario, values_from = c(area)) %>%
  mutate(DifCornShock = CORN1BG - BASE) %>%
  mutate(DifSoyShock = SOY1BG - BASE)

cum_soil_emiss_sums<-wide_sum_soil_emiss %>%
   group_by(Series, year) %>% 
  summarise(across(where(is.numeric), sum)) %>%
#calculate the cumulative emissions
  mutate(aggDifCorncount = cumsum(DifCornShock)) %>%
  mutate(aggDifSoycount = cumsum(DifSoyShock))


mergedData<-merge(wide_sum_soil_emiss, wide_sum_veg, 
                  by=c("Category", "year"), all=TRUE) %>%
#rename all of the columns after the merge
               rename( c( "BASE.soil" ="BASE.x", 
                           "BASE.veg" = "BASE.y", 
                           "CORN1BG.soil" =  "CORN1BG.x", 
                           "CORN1BG.veg" = "CORN1BG.y",
                          "SOY1BG.soil" =  "SOY1BG.x", 
                           "SOY1BG.veg" = "SOY1BG.y",
                          "DifCornShock.soil" = "DifCornShock.x", 
                          "DifSoyShock.soil" = "DifSoyShock.x", 
                           "DifCornShock.veg" = "DifCornShock.y", 
                          "DifSoyShock.veg" = "DifSoyShock.y" )) %>%
                mutate(netDifCornShock = DifCornShock.soil + DifCornShock.veg) %>%
                mutate(netDifSoyShock = DifSoyShock.soil + DifSoyShock.veg)

sum_merged_data <- mergedData %>%
   group_by(Series, year) %>% 
  summarise(across(where(is.numeric), sum)) 
```

Net and Cumulative Emissions 
=======================================================================

Row
-----------------------------------------------------------------------
### Total Net Corn Shock Emissions Over Baseline

```{r}



net_emiss_CS_Models.plt<-ggplot(data= sum_merged_data %>%
                                    filter(year > 2015), 
                         aes(x=year, y=netDifCornShock, group=Series, color=Series))+
  geom_line(aes(), size=2) +
  #add a title
  #ggtitle("Total Net Corn Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)

ggplotly(net_emiss_CS_Models.plt)
```

### Total Net Soy Shock Emissions Over Baseline
```{r}
net_emiss_SS_Models.plt<-ggplot(data= sum_merged_data, 
                         aes(x=year, y=netDifSoyShock, group=Series, color=Series))+
  geom_line(aes(), size=2) +
  #add a title
  #ggtitle("Total Net Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)

ggplotly(net_emiss_SS_Models.plt)
```

Row
-----------------------------------------------------------------------


Soil Emission Plots
=======================================================================

Row
-----------------------------------------------------------------------

### Total Corn Shock Emissions Over Baseline

```{r}

  
cum_soil_emiss_sums_CS_Models.plt<-ggplot(data= cum_soil_emiss_sums %>%
                                    filter(year > 2015), 
                         aes(x=year, y=DifCornShock, group=Series))+
  geom_line(aes(color=Series), size=2) +
  #add a title
  ggtitle("Total Corn Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)
# Use hollow circles
ggplotly(cum_soil_emiss_sums_CS_Models.plt)
```


### Total Soy Shock Emissions Over Baseline

```{r}
cum_soil_emiss_sums_SS_Models.plt<-ggplot(data= cum_soil_emiss_sums %>%
                                    filter(year > 2015), 
                         aes(x=year, y=DifSoyShock, group=Series))+
  geom_line(aes(color=Series), size=2) +
  #add a title
  #ggtitle("Total Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)



ggplotly(cum_soil_emiss_sums_SS_Models.plt)
```

Row
-----------------------------------------------------------------------

### geom_smooth with Loess Smoothed Fit

```{r}
tot_cum_soil_emiss_sums_CS_Models.plt<-ggplot(data= cum_soil_emiss_sums %>%
                                    filter(year > 2015), 
                         aes(x=year, y=aggDifCorncount, group=Series))+
  geom_line(aes(color=Series), size=2) +
  #add a title
  ggtitle("Soil Cumulative Corn Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)



# Add a loess smoothed fit curve with confidence region
ggplotly(tot_cum_soil_emiss_sums_CS_Models.plt)
```

### Constraining Slope with stat_smooth

```{r}
tot_cum_soil_emiss_sums_SS_Models.plt<-ggplot(data= cum_soil_emiss_sums %>%
                                    filter(year > 2015), 
                         aes(x=year, y=aggDifSoycount, group=Series))+
  geom_line(aes(color=Series), size=2) +
  #add a title
  ggtitle("Soil Cumulative Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)


ggplotly(tot_cum_soil_emiss_sums_SS_Models.plt)
```

Vegetation and Land Use Plots
=======================================================================

Row
-----------------------------------------------------------------------

### stat_density Example

```{r}
dfGamma = data.frame(nu75 = rgamma(100, 0.75),
           nu1 = rgamma(100, 1),
           nu2 = rgamma(100, 2))

dfGamma = stack(dfGamma)

p <- ggplot(dfGamma, aes(x = values)) +
            stat_density(aes(group = ind, color = ind),position="identity",geom="line")
ggplotly(p)
```

### Add Conditional Density Curves to Plot

```{r}
dim1 <- c(rnorm(100, mean=1), rnorm(100, mean=4))
dim2 <- rnorm(200, mean=1)
cat <- factor(c(rep("a", 100), rep("b", 100)))
mydf <- data.frame(cbind(dim2, dim1, cat))
p <- ggplot(data=mydf, aes(x=dim1, y=dim2, colour=as.factor(cat))) +
  geom_point() +
  stat_density(aes(x=dim1, y=(-2+(..scaled..))),
               position="identity", geom="line")

# extract the x range to make the new densities align with y-axis
xrange <- ggplot_build(p)$layout$panel_scales_x[[1]]$range$range

## Get densities of dim2
ds <- do.call(rbind, lapply(unique(mydf$cat), function(lev) {
    dens <- with(mydf, density(dim2[cat==lev]))
    data.frame(x=dens$y+xrange[1], y=dens$x, cat=lev)
}))

p <- p + geom_path(data=ds, aes(x=x, y=y, color=factor(cat)))

ggplotly(p)
```

Row
-----------------------------------------------------------------------

### geom_density and facet_wrap Together

```{r}
dd<-data.frame(matrix(rnorm(144, mean=2, sd=2),72,2),c(rep("A",24),rep("B",24),rep("C",24)))
colnames(dd) <- c("x_value", "Predicted_value",  "State_CD")

dd <- data.frame(
  predicted = rnorm(72, mean = 2, sd = 2),
  state = rep(c("A", "B", "C"), each = 24)
)

grid <- with(dd, seq(min(predicted), max(predicted), length = 100))
normaldens <- ddply(dd, "state", function(df) {
  data.frame(
    predicted = grid,
    density = dnorm(grid, mean(df$predicted), sd(df$predicted))
  )
})

p <- ggplot(dd, aes(predicted))  +
            geom_density() +
            geom_line(aes(y = density), data = normaldens, colour = "red") +
            facet_wrap(~ state)
ggplotly(p)
```

### Density and Scatterplot Overlay Using geom_density

```{r}
df <- data.frame(x <- rchisq(1000, 10, 10),
                 y <- rnorm(1000))

p <- ggplot(df, aes(x, y)) + 
     geom_point(alpha = 0.5) + 
     geom_density_2d() + 
     theme(panel.background = element_rect(fill = '#ffffff'))

ggplotly(p)
```